services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/work
      - cargo-registry:/usr/local/cargo/registry
      - cargo-git:/usr/local/cargo/git
      - cargo-target:/work/rust/target
    working_dir: /work

volumes:
  cargo-registry:
  cargo-git:
  cargo-target:
