// AUTO-GENERATED by tools/gen-ts-types.py — DO NOT EDIT
// Source: rust/core/fields.yaml

export interface FakerOptions {
  seed?: string;
  locale?: string;
  tz?: string;
  since?: number;
  until?: number;
}

interface BaseOpts {
  upper?: true;
  lower?: true;
  capitalize?: true;
  omit?: number;
}

interface IntegerOpts extends BaseOpts {
  range?: [number, number];
  asc?: true;
  desc?: true;
}

interface FloatOpts extends BaseOpts {
  range?: [number, number];
  asc?: true;
  desc?: true;
}

interface BitOpts extends BaseOpts {
  sign?: true;
}

interface DigitsOpts extends BaseOpts {
  range?: [number, number];
  asc?: true;
  desc?: true;
  length?: number;
}

interface LettersOpts extends BaseOpts {
  length?: number;
}

interface AlnumOpts extends BaseOpts {
  length?: number;
}

interface Base64Opts extends BaseOpts {
  length?: number;
}

interface HexOpts extends BaseOpts {
  byte?: true;
  length?: number;
}

interface ColorOpts extends BaseOpts {
  hex?: true;
  rgb?: true;
  rgba?: true;
}

interface UuidOpts extends BaseOpts {
  plain?: true;
}

interface TimestampOpts extends BaseOpts {
  unix?: true;
  ms?: true;
  log?: true;
  range?: [number, number];
  asc?: true;
  desc?: true;
}

interface DateOpts extends BaseOpts {
  us?: true;
  eu?: true;
  range?: [number, number];
  asc?: true;
  desc?: true;
}

interface BirthdateOpts extends BaseOpts {
  us?: true;
  eu?: true;
  range?: [number, number];
}

interface AgeOpts extends BaseOpts {
  range?: [number, number];
  asc?: true;
  desc?: true;
}

interface UsernameOpts extends BaseOpts {
  xuniq?: true;
}

interface LoginNameOpts extends BaseOpts {
  xuniq?: true;
}

interface SocialHandleOpts extends BaseOpts {
  xuniq?: true;
}

interface NicknameOpts extends BaseOpts {
  xuniq?: true;
}

interface EmailOpts extends BaseOpts {
  xuniq?: true;
}

interface PhoneOpts extends BaseOpts {
  e164?: true;
  intl?: true;
  plain?: true;
}

interface CountryCodeOpts extends BaseOpts {
  alpha3?: true;
  numeric?: true;
}

interface LocaleCodeOpts extends BaseOpts {
  short?: true;
  underscore?: true;
}

interface CreditCardOpts extends BaseOpts {
  space?: true;
  dash?: true;
  plain?: true;
}

interface IbanOpts extends BaseOpts {
  plain?: true;
}

interface AmountOpts extends BaseOpts {
  dot?: true;
  comma?: true;
  plain?: true;
  usd?: true;
  eur?: true;
  gbp?: true;
  range?: [number, number];
  asc?: true;
  desc?: true;
}

interface CurrencyCodeOpts extends BaseOpts {
  crypto?: true;
}

interface PasswordOpts extends BaseOpts {
  pin?: true;
  memorable?: true;
  mixed?: true;
  strong?: true;
  length?: number;
}

interface SsnOpts extends BaseOpts {
  plain?: true;
}

interface PassportOpts extends BaseOpts {
  international?: true;
  internal?: true;
}

interface CpfOpts extends BaseOpts {
  plain?: true;
}

interface CnpjOpts extends BaseOpts {
  plain?: true;
}

interface MacOpts extends BaseOpts {
  plain?: true;
  dot?: true;
}

interface UrlOpts extends BaseOpts {
  http?: true;
  https?: true;
  ftp?: true;
  ws?: true;
  wss?: true;
  ssh?: true;
}

interface PortOpts extends BaseOpts {
  system?: true;
  registered?: true;
  dynamic?: true;
  unprivileged?: true;
  service?: true;
}

interface LatencyOpts extends BaseOpts {
  fast?: true;
  slow?: true;
  seconds?: true;
  asc?: true;
  desc?: true;
}

interface ImageUrlOpts extends BaseOpts {
  "1x1"?: true;
  "4x3"?: true;
  "3x2"?: true;
  "16x9"?: true;
  "21x9"?: true;
  "9x16"?: true;
  "3x4"?: true;
  "2x3"?: true;
}

interface TxHashOpts extends BaseOpts {
  btc?: true;
}

interface EnvVarOpts extends BaseOpts {
  multi?: true;
}

export type FieldName =
  | "integer"
  | "float"
  | "boolean"
  | "digit"
  | "bit"
  | "trit"
  | "enum"
  | "serial"
  | "letter"
  | "trigram"
  | "digits"
  | "letters"
  | "alnum"
  | "base64"
  | "hex"
  | "word"
  | "message"
  | "emoji"
  | "color"
  | "uuid"
  | "bz"
  | "dice"
  | "excuse"
  | "mball"
  | "timestamp"
  | "date"
  | "name"
  | "first-name"
  | "last-name"
  | "middle-name"
  | "birthdate"
  | "age"
  | "gender"
  | "username"
  | "login-name"
  | "social-handle"
  | "nickname"
  | "biometric-id"
  | "student-id"
  | "email"
  | "phone"
  | "address"
  | "street-address"
  | "city"
  | "state"
  | "postal-code"
  | "country"
  | "latitude"
  | "longitude"
  | "country-code"
  | "phone-code"
  | "language-code"
  | "locale-code"
  | "timezone"
  | "credit-card"
  | "cvv"
  | "iban"
  | "swift-bic"
  | "routing-number"
  | "bank-account"
  | "tax-id"
  | "amount"
  | "currency-code"
  | "currency-symbol"
  | "password"
  | "jwt"
  | "bearer-token"
  | "api-key"
  | "totp-secret"
  | "oauth-client-secret"
  | "aws-access-key"
  | "aws-secret-key"
  | "stripe-key"
  | "github-pat"
  | "gitlab-token"
  | "openai-key"
  | "sendgrid-key"
  | "twilio-sid"
  | "twilio-token"
  | "slack-bot-token"
  | "slack-user-token"
  | "datadog-key"
  | "sentry-dsn"
  | "vault-token"
  | "npm-token"
  | "vercel-token"
  | "supabase-key"
  | "telegram-token"
  | "discord-webhook"
  | "gcp-key"
  | "azure-key"
  | "cloudflare-token"
  | "pagerduty-key"
  | "newrelic-key"
  | "splunk-token"
  | "heroku-key"
  | "firebase-key"
  | "ssh-private-key"
  | "ssh-public-key"
  | "connection-string"
  | "anthropic-key"
  | "session-id"
  | "passkey-id"
  | "facebook-token"
  | "google-token"
  | "apple-token"
  | "refresh-token"
  | "csrf-token"
  | "basic-auth"
  | "ssn"
  | "passport"
  | "drivers-license"
  | "national-id"
  | "cpf"
  | "sin"
  | "tfn"
  | "nino"
  | "nhs-number"
  | "nir"
  | "codice-fiscale"
  | "dni"
  | "nie"
  | "bsn"
  | "personnummer"
  | "steuer-id"
  | "cuil"
  | "jmbg"
  | "tc-kimlik"
  | "pesel"
  | "curp"
  | "rut"
  | "inn"
  | "ipn"
  | "abn"
  | "cnpj"
  | "oib"
  | "amka"
  | "rodne-cislo"
  | "szemelyi-szam"
  | "hetu"
  | "cpr"
  | "fodselsnummer"
  | "pps"
  | "emso"
  | "egn"
  | "idnp"
  | "health-card"
  | "cedula"
  | "aadhaar"
  | "pan"
  | "cccd"
  | "shenfenzheng"
  | "ip"
  | "ipv6"
  | "mac"
  | "url"
  | "auth-url"
  | "internal-url"
  | "dns-record"
  | "browser-cookie"
  | "user-agent"
  | "mime-type"
  | "http-method"
  | "http-status"
  | "port"
  | "latency"
  | "image-url"
  | "twitter-url"
  | "linkedin-url"
  | "facebook-url"
  | "instagram-url"
  | "github-url"
  | "telegram-url"
  | "youtube-url"
  | "webhook-url"
  | "btc-address"
  | "eth-address"
  | "sol-address"
  | "tx-hash"
  | "pgp-fingerprint"
  | "company-name"
  | "ein"
  | "vat-number"
  | "duns"
  | "lei"
  | "job-title"
  | "ldap-dn"
  | "employee-id"
  | "court-case"
  | "mrn"
  | "npi"
  | "insurance-id"
  | "medicare-id"
  | "icd-10"
  | "cpt-code"
  | "ndc"
  | "rx-number"
  | "project-code"
  | "jira-id"
  | "github-issue"
  | "commit-hash"
  | "semver"
  | "docker-image"
  | "slack-channel"
  | "sentry-issue"
  | "pagerduty-incident"
  | "file-path"
  | "s3-path"
  | "env-var"
  | "vin"
  | "license-plate"
  | "imei"
  | "imsi"
  | "device-id";

export interface RecordOpts {
  n?: number;
  ctx?: "strict" | "loose";
  corrupt?: "low" | "mid" | "high" | "extreme";
}

export interface ValidateOpts {
  ctx?: "strict" | "loose";
  corrupt?: "low" | "mid" | "high" | "extreme";
}

export class SeedFaker {
  constructor(opts?: FakerOptions);

  field(name: "integer", opts?: IntegerOpts): string;
  field(name: "float", opts?: FloatOpts): string;
  field(name: "boolean", opts?: BaseOpts): string;
  field(name: "digit", opts?: BaseOpts): string;
  field(name: "bit", opts?: BitOpts): string;
  field(name: "trit", opts?: BaseOpts): string;
  field(name: "enum", opts?: BaseOpts): string;
  field(name: "serial", opts?: BaseOpts): string;
  field(name: "letter", opts?: BaseOpts): string;
  field(name: "trigram", opts?: BaseOpts): string;
  field(name: "digits", opts?: DigitsOpts): string;
  field(name: "letters", opts?: LettersOpts): string;
  field(name: "alnum", opts?: AlnumOpts): string;
  field(name: "base64", opts?: Base64Opts): string;
  field(name: "hex", opts?: HexOpts): string;
  field(name: "word", opts?: BaseOpts): string;
  field(name: "message", opts?: BaseOpts): string;
  field(name: "emoji", opts?: BaseOpts): string;
  field(name: "color", opts?: ColorOpts): string;
  field(name: "uuid", opts?: UuidOpts): string;
  field(name: "bz", opts?: BaseOpts): string;
  field(name: "dice", opts?: BaseOpts): string;
  field(name: "excuse", opts?: BaseOpts): string;
  field(name: "mball", opts?: BaseOpts): string;
  field(name: "timestamp", opts?: TimestampOpts): string;
  field(name: "date", opts?: DateOpts): string;
  field(name: "name", opts?: BaseOpts): string;
  field(name: "first-name", opts?: BaseOpts): string;
  field(name: "last-name", opts?: BaseOpts): string;
  field(name: "middle-name", opts?: BaseOpts): string;
  field(name: "birthdate", opts?: BirthdateOpts): string;
  field(name: "age", opts?: AgeOpts): string;
  field(name: "gender", opts?: BaseOpts): string;
  field(name: "username", opts?: UsernameOpts): string;
  field(name: "login-name", opts?: LoginNameOpts): string;
  field(name: "social-handle", opts?: SocialHandleOpts): string;
  field(name: "nickname", opts?: NicknameOpts): string;
  field(name: "biometric-id", opts?: BaseOpts): string;
  field(name: "student-id", opts?: BaseOpts): string;
  field(name: "email", opts?: EmailOpts): string;
  field(name: "phone", opts?: PhoneOpts): string;
  field(name: "address", opts?: BaseOpts): string;
  field(name: "street-address", opts?: BaseOpts): string;
  field(name: "city", opts?: BaseOpts): string;
  field(name: "state", opts?: BaseOpts): string;
  field(name: "postal-code", opts?: BaseOpts): string;
  field(name: "country", opts?: BaseOpts): string;
  field(name: "latitude", opts?: BaseOpts): string;
  field(name: "longitude", opts?: BaseOpts): string;
  field(name: "country-code", opts?: CountryCodeOpts): string;
  field(name: "phone-code", opts?: BaseOpts): string;
  field(name: "language-code", opts?: BaseOpts): string;
  field(name: "locale-code", opts?: LocaleCodeOpts): string;
  field(name: "timezone", opts?: BaseOpts): string;
  field(name: "credit-card", opts?: CreditCardOpts): string;
  field(name: "cvv", opts?: BaseOpts): string;
  field(name: "iban", opts?: IbanOpts): string;
  field(name: "swift-bic", opts?: BaseOpts): string;
  field(name: "routing-number", opts?: BaseOpts): string;
  field(name: "bank-account", opts?: BaseOpts): string;
  field(name: "tax-id", opts?: BaseOpts): string;
  field(name: "amount", opts?: AmountOpts): string;
  field(name: "currency-code", opts?: CurrencyCodeOpts): string;
  field(name: "currency-symbol", opts?: BaseOpts): string;
  field(name: "password", opts?: PasswordOpts): string;
  field(name: "jwt", opts?: BaseOpts): string;
  field(name: "bearer-token", opts?: BaseOpts): string;
  field(name: "api-key", opts?: BaseOpts): string;
  field(name: "totp-secret", opts?: BaseOpts): string;
  field(name: "oauth-client-secret", opts?: BaseOpts): string;
  field(name: "aws-access-key", opts?: BaseOpts): string;
  field(name: "aws-secret-key", opts?: BaseOpts): string;
  field(name: "stripe-key", opts?: BaseOpts): string;
  field(name: "github-pat", opts?: BaseOpts): string;
  field(name: "gitlab-token", opts?: BaseOpts): string;
  field(name: "openai-key", opts?: BaseOpts): string;
  field(name: "sendgrid-key", opts?: BaseOpts): string;
  field(name: "twilio-sid", opts?: BaseOpts): string;
  field(name: "twilio-token", opts?: BaseOpts): string;
  field(name: "slack-bot-token", opts?: BaseOpts): string;
  field(name: "slack-user-token", opts?: BaseOpts): string;
  field(name: "datadog-key", opts?: BaseOpts): string;
  field(name: "sentry-dsn", opts?: BaseOpts): string;
  field(name: "vault-token", opts?: BaseOpts): string;
  field(name: "npm-token", opts?: BaseOpts): string;
  field(name: "vercel-token", opts?: BaseOpts): string;
  field(name: "supabase-key", opts?: BaseOpts): string;
  field(name: "telegram-token", opts?: BaseOpts): string;
  field(name: "discord-webhook", opts?: BaseOpts): string;
  field(name: "gcp-key", opts?: BaseOpts): string;
  field(name: "azure-key", opts?: BaseOpts): string;
  field(name: "cloudflare-token", opts?: BaseOpts): string;
  field(name: "pagerduty-key", opts?: BaseOpts): string;
  field(name: "newrelic-key", opts?: BaseOpts): string;
  field(name: "splunk-token", opts?: BaseOpts): string;
  field(name: "heroku-key", opts?: BaseOpts): string;
  field(name: "firebase-key", opts?: BaseOpts): string;
  field(name: "ssh-private-key", opts?: BaseOpts): string;
  field(name: "ssh-public-key", opts?: BaseOpts): string;
  field(name: "connection-string", opts?: BaseOpts): string;
  field(name: "anthropic-key", opts?: BaseOpts): string;
  field(name: "session-id", opts?: BaseOpts): string;
  field(name: "passkey-id", opts?: BaseOpts): string;
  field(name: "facebook-token", opts?: BaseOpts): string;
  field(name: "google-token", opts?: BaseOpts): string;
  field(name: "apple-token", opts?: BaseOpts): string;
  field(name: "refresh-token", opts?: BaseOpts): string;
  field(name: "csrf-token", opts?: BaseOpts): string;
  field(name: "basic-auth", opts?: BaseOpts): string;
  field(name: "ssn", opts?: SsnOpts): string;
  field(name: "passport", opts?: PassportOpts): string;
  field(name: "drivers-license", opts?: BaseOpts): string;
  field(name: "national-id", opts?: BaseOpts): string;
  field(name: "cpf", opts?: CpfOpts): string;
  field(name: "sin", opts?: BaseOpts): string;
  field(name: "tfn", opts?: BaseOpts): string;
  field(name: "nino", opts?: BaseOpts): string;
  field(name: "nhs-number", opts?: BaseOpts): string;
  field(name: "nir", opts?: BaseOpts): string;
  field(name: "codice-fiscale", opts?: BaseOpts): string;
  field(name: "dni", opts?: BaseOpts): string;
  field(name: "nie", opts?: BaseOpts): string;
  field(name: "bsn", opts?: BaseOpts): string;
  field(name: "personnummer", opts?: BaseOpts): string;
  field(name: "steuer-id", opts?: BaseOpts): string;
  field(name: "cuil", opts?: BaseOpts): string;
  field(name: "jmbg", opts?: BaseOpts): string;
  field(name: "tc-kimlik", opts?: BaseOpts): string;
  field(name: "pesel", opts?: BaseOpts): string;
  field(name: "curp", opts?: BaseOpts): string;
  field(name: "rut", opts?: BaseOpts): string;
  field(name: "inn", opts?: BaseOpts): string;
  field(name: "ipn", opts?: BaseOpts): string;
  field(name: "abn", opts?: BaseOpts): string;
  field(name: "cnpj", opts?: CnpjOpts): string;
  field(name: "oib", opts?: BaseOpts): string;
  field(name: "amka", opts?: BaseOpts): string;
  field(name: "rodne-cislo", opts?: BaseOpts): string;
  field(name: "szemelyi-szam", opts?: BaseOpts): string;
  field(name: "hetu", opts?: BaseOpts): string;
  field(name: "cpr", opts?: BaseOpts): string;
  field(name: "fodselsnummer", opts?: BaseOpts): string;
  field(name: "pps", opts?: BaseOpts): string;
  field(name: "emso", opts?: BaseOpts): string;
  field(name: "egn", opts?: BaseOpts): string;
  field(name: "idnp", opts?: BaseOpts): string;
  field(name: "health-card", opts?: BaseOpts): string;
  field(name: "cedula", opts?: BaseOpts): string;
  field(name: "aadhaar", opts?: BaseOpts): string;
  field(name: "pan", opts?: BaseOpts): string;
  field(name: "cccd", opts?: BaseOpts): string;
  field(name: "shenfenzheng", opts?: BaseOpts): string;
  field(name: "ip", opts?: BaseOpts): string;
  field(name: "ipv6", opts?: BaseOpts): string;
  field(name: "mac", opts?: MacOpts): string;
  field(name: "url", opts?: UrlOpts): string;
  field(name: "auth-url", opts?: BaseOpts): string;
  field(name: "internal-url", opts?: BaseOpts): string;
  field(name: "dns-record", opts?: BaseOpts): string;
  field(name: "browser-cookie", opts?: BaseOpts): string;
  field(name: "user-agent", opts?: BaseOpts): string;
  field(name: "mime-type", opts?: BaseOpts): string;
  field(name: "http-method", opts?: BaseOpts): string;
  field(name: "http-status", opts?: BaseOpts): string;
  field(name: "port", opts?: PortOpts): string;
  field(name: "latency", opts?: LatencyOpts): string;
  field(name: "image-url", opts?: ImageUrlOpts): string;
  field(name: "twitter-url", opts?: BaseOpts): string;
  field(name: "linkedin-url", opts?: BaseOpts): string;
  field(name: "facebook-url", opts?: BaseOpts): string;
  field(name: "instagram-url", opts?: BaseOpts): string;
  field(name: "github-url", opts?: BaseOpts): string;
  field(name: "telegram-url", opts?: BaseOpts): string;
  field(name: "youtube-url", opts?: BaseOpts): string;
  field(name: "webhook-url", opts?: BaseOpts): string;
  field(name: "btc-address", opts?: BaseOpts): string;
  field(name: "eth-address", opts?: BaseOpts): string;
  field(name: "sol-address", opts?: BaseOpts): string;
  field(name: "tx-hash", opts?: TxHashOpts): string;
  field(name: "pgp-fingerprint", opts?: BaseOpts): string;
  field(name: "company-name", opts?: BaseOpts): string;
  field(name: "ein", opts?: BaseOpts): string;
  field(name: "vat-number", opts?: BaseOpts): string;
  field(name: "duns", opts?: BaseOpts): string;
  field(name: "lei", opts?: BaseOpts): string;
  field(name: "job-title", opts?: BaseOpts): string;
  field(name: "ldap-dn", opts?: BaseOpts): string;
  field(name: "employee-id", opts?: BaseOpts): string;
  field(name: "court-case", opts?: BaseOpts): string;
  field(name: "mrn", opts?: BaseOpts): string;
  field(name: "npi", opts?: BaseOpts): string;
  field(name: "insurance-id", opts?: BaseOpts): string;
  field(name: "medicare-id", opts?: BaseOpts): string;
  field(name: "icd-10", opts?: BaseOpts): string;
  field(name: "cpt-code", opts?: BaseOpts): string;
  field(name: "ndc", opts?: BaseOpts): string;
  field(name: "rx-number", opts?: BaseOpts): string;
  field(name: "project-code", opts?: BaseOpts): string;
  field(name: "jira-id", opts?: BaseOpts): string;
  field(name: "github-issue", opts?: BaseOpts): string;
  field(name: "commit-hash", opts?: BaseOpts): string;
  field(name: "semver", opts?: BaseOpts): string;
  field(name: "docker-image", opts?: BaseOpts): string;
  field(name: "slack-channel", opts?: BaseOpts): string;
  field(name: "sentry-issue", opts?: BaseOpts): string;
  field(name: "pagerduty-incident", opts?: BaseOpts): string;
  field(name: "file-path", opts?: BaseOpts): string;
  field(name: "s3-path", opts?: BaseOpts): string;
  field(name: "env-var", opts?: EnvVarOpts): string;
  field(name: "vin", opts?: BaseOpts): string;
  field(name: "license-plate", opts?: BaseOpts): string;
  field(name: "imei", opts?: BaseOpts): string;
  field(name: "imsi", opts?: BaseOpts): string;
  field(name: "device-id", opts?: BaseOpts): string;
  field(name: string, opts?: BaseOpts): string;

  record(fields: (FieldName | string)[], opts?: ValidateOpts): Record<string, string>;

  records(fields: (FieldName | string)[], opts?: RecordOpts): Record<string, string>[];

  validate(fields: (FieldName | string)[], opts?: ValidateOpts): void;

  static fields(): FieldName[];
  static fingerprint(): string;
}
