# AUTO-GENERATED by tools/gen-py-types.py from rust/core/fields.yaml — DO NOT EDIT

from typing import Literal, overload

def _build_spec(name: str, kwargs: dict) -> str: ...

class SeedFaker:
    def __init__(
        self,
        seed: str | None = ...,
        locale: str | None = ...,
        tz: str | None = ...,
        since: int | None = ...,
        until: int | None = ...,
    ) -> None: ...
    @overload
    def field(
        self,
        name: Literal["integer"],
        *,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["float"],
        *,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["boolean"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["digit"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["bit"],
        *,
        sign: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["trit"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["enum"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["serial"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["letter"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["trigram"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["digits"],
        *,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        length: int = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["letters"],
        *,
        length: int = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["alnum"],
        *,
        length: int = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["base64"],
        *,
        length: int = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["hex"],
        *,
        byte: bool = ...,
        length: int = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["word"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["message"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["emoji"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["color"],
        *,
        hex: bool = ...,
        rgb: bool = ...,
        rgba: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["uuid"],
        *,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["bz"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["dice"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["excuse"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["mball"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["timestamp"],
        *,
        unix: bool = ...,
        ms: bool = ...,
        log: bool = ...,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["date"],
        *,
        us: bool = ...,
        eu: bool = ...,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["name"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["first-name"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["last-name"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["middle-name"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["birthdate"],
        *,
        us: bool = ...,
        eu: bool = ...,
        range: tuple[int, int] = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["age"],
        *,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["gender"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["username"],
        *,
        xuniq: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["login-name"],
        *,
        xuniq: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["social-handle"],
        *,
        xuniq: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["nickname"],
        *,
        xuniq: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["biometric-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["student-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["email"],
        *,
        xuniq: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["phone"],
        *,
        e164: bool = ...,
        intl: bool = ...,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["address"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["street-address"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["city"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["state"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["postal-code"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["country"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["latitude"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["longitude"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["country-code"],
        *,
        alpha3: bool = ...,
        numeric: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["phone-code"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["language-code"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["locale-code"],
        *,
        short: bool = ...,
        underscore: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["timezone"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["credit-card"],
        *,
        space: bool = ...,
        dash: bool = ...,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cvv"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["iban"],
        *,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["swift-bic"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["routing-number"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["bank-account"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["tax-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["amount"],
        *,
        dot: bool = ...,
        comma: bool = ...,
        plain: bool = ...,
        usd: bool = ...,
        eur: bool = ...,
        gbp: bool = ...,
        range: tuple[int, int] = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["currency-code"],
        *,
        crypto: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["currency-symbol"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["password"],
        *,
        pin: bool = ...,
        memorable: bool = ...,
        mixed: bool = ...,
        strong: bool = ...,
        length: int = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["jwt"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["bearer-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["api-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["totp-secret"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["oauth-client-secret"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["aws-access-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["aws-secret-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["stripe-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["github-pat"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["gitlab-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["openai-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["sendgrid-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["twilio-sid"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["twilio-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["slack-bot-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["slack-user-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["datadog-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["sentry-dsn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["vault-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["npm-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["vercel-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["supabase-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["telegram-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["discord-webhook"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["gcp-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["azure-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cloudflare-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["pagerduty-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["newrelic-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["splunk-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["heroku-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["firebase-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ssh-private-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ssh-public-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["connection-string"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["anthropic-key"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["session-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["passkey-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["facebook-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["google-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["apple-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["refresh-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["csrf-token"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["basic-auth"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ssn"],
        *,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["passport"],
        *,
        international: bool = ...,
        internal: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["drivers-license"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["national-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cpf"],
        *,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["sin"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["tfn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["nino"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["nhs-number"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["nir"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["codice-fiscale"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["dni"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["nie"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["bsn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["personnummer"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["steuer-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cuil"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["jmbg"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["tc-kimlik"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["pesel"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["curp"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["rut"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["inn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ipn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["abn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cnpj"],
        *,
        plain: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["oib"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["amka"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["rodne-cislo"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["szemelyi-szam"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["hetu"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cpr"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["fodselsnummer"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["pps"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["emso"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["egn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["idnp"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["health-card"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cedula"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["aadhaar"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["pan"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cccd"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["shenfenzheng"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ip"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ipv6"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["mac"],
        *,
        plain: bool = ...,
        dot: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["url"],
        *,
        http: bool = ...,
        https: bool = ...,
        ftp: bool = ...,
        ws: bool = ...,
        wss: bool = ...,
        ssh: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["auth-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["internal-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["dns-record"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["browser-cookie"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["user-agent"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["mime-type"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["http-method"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["http-status"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["port"],
        *,
        system: bool = ...,
        registered: bool = ...,
        dynamic: bool = ...,
        unprivileged: bool = ...,
        service: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["latency"],
        *,
        fast: bool = ...,
        slow: bool = ...,
        seconds: bool = ...,
        asc: bool = ...,
        desc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["image-url"],
        *,
        r1x1: bool = ...,
        r4x3: bool = ...,
        r3x2: bool = ...,
        r16x9: bool = ...,
        r21x9: bool = ...,
        r9x16: bool = ...,
        r3x4: bool = ...,
        r2x3: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["twitter-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["linkedin-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["facebook-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["instagram-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["github-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["telegram-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["youtube-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["webhook-url"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["btc-address"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["eth-address"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["sol-address"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["tx-hash"],
        *,
        btc: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["pgp-fingerprint"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["company-name"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ein"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["vat-number"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["duns"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["lei"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["job-title"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ldap-dn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["employee-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["court-case"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["mrn"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["npi"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["insurance-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["medicare-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["icd-10"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["cpt-code"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["ndc"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["rx-number"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["project-code"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["jira-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["github-issue"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["commit-hash"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["semver"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["docker-image"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["slack-channel"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["sentry-issue"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["pagerduty-incident"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["file-path"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["s3-path"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["env-var"],
        *,
        multi: bool = ...,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["vin"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["license-plate"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["imei"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["imsi"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    @overload
    def field(
        self,
        name: Literal["device-id"],
        *,
        upper: bool = ...,
        lower: bool = ...,
        capitalize: bool = ...,
        omit: int = ...,
    ) -> str: ...
    def field(self, name: str, **kwargs: object) -> str: ...
    def record(
        self,
        fields: list[str],
        *,
        ctx: str | None = ...,
        corrupt: str | None = ...,
    ) -> dict[str, str]: ...
    def records(
        self,
        fields: list[str],
        *,
        n: int = ...,
        ctx: str | None = ...,
        corrupt: str | None = ...,
    ) -> list[dict[str, str]]: ...
    @staticmethod
    def validate(
        fields: list[str],
        *,
        ctx: str | None = ...,
        corrupt: str | None = ...,
    ) -> None: ...
    @staticmethod
    def fields() -> list[str]: ...
    @staticmethod
    def fingerprint() -> str: ...
