#!/usr/bin/env python3
"""Generate field_gen.rs from fields.yaml.

Reads rust/core/fields.yaml and writes rust/core/src/field_gen.rs.
Usage: python3 tools/gen-fields.py
"""

import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("pyyaml required: pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / "rust" / "core" / "fields.yaml"
OUT_PATH = ROOT / "rust" / "core" / "src" / "field_gen.rs"
GEN_DIR = ROOT / "rust" / "core" / "src" / "gen"
MOD_RS = GEN_DIR / "mod.rs"


def main():
    with open(YAML_PATH) as f:
        data = yaml.safe_load(f)

    next_id = data["next_id"]
    fields = data["fields"]

    # Read mod.rs to know declared modules
    mod_rs_text = MOD_RS.read_text()
    declared_modules = set()
    for line in mod_rs_text.splitlines():
        line = line.strip()
        if line.startswith("pub mod ") and line.endswith(";"):
            mod_name = line[8:-1].strip()
            declared_modules.add(mod_name)

    # Validate
    seen_ids = set()
    seen_names = set()
    max_num = 0
    errors = []

    for entry in fields:
        fid = entry["id"]
        name = entry["name"]
        gen_module = entry["gen"]

        # Duplicate ID
        if fid in seen_ids:
            errors.append(f"duplicate id '{fid}'")
        seen_ids.add(fid)

        # Duplicate name
        if name in seen_names:
            errors.append(f"duplicate name '{name}' (id={fid})")
        seen_names.add(name)

        # ID format
        num = int(fid[1:])
        if num > max_num:
            max_num = num

        # Description
        desc = entry.get("description", "")
        if not desc:
            errors.append(f"field '{fid}' ({name}) missing description")
        elif len(desc) > 80:
            errors.append(
                f"field '{fid}' ({name}) description exceeds 80 chars ({len(desc)})"
            )

        # Module file exists
        mod_file = GEN_DIR / f"{gen_module}.rs"
        if not mod_file.exists():
            errors.append(
                f"field '{fid}' ({name}): module file gen/{gen_module}.rs not found"
            )

        # Module declared in mod.rs
        if gen_module not in declared_modules:
            errors.append(
                f"field '{fid}' ({name}): module '{gen_module}' not declared in gen/mod.rs"
            )

    if next_id < max_num + 1:
        errors.append(f"next_id ({next_id}) must be >= {max_num + 1}")

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    # Groups
    if "groups" in data:
        groups = data["groups"]
    else:
        groups = []
        seen_groups = set()
        for entry in fields:
            g = entry["group"]
            if g not in seen_groups:
                groups.append(g)
                seen_groups.add(g)

    field_groups = {e["group"] for e in fields}
    missing = field_groups - set(groups)
    if missing:
        sys.exit(f"ERROR: groups missing from groups list: {missing}")

    # Build modifiers and capabilities maps
    modifiers = {}
    capabilities = {}
    for entry in fields:
        fid = entry["id"]
        mods = entry.get("modifiers")
        caps = []
        if mods:
            modifiers[fid] = ", ".join(mods)
            caps.extend(mods)
        if entry.get("length"):
            caps.append("N")
        if entry.get("range"):
            caps.append("range")
        if entry.get("ordering"):
            caps.append("asc/desc")
        if caps:
            capabilities[fid] = ", ".join(caps)

    # Generate Rust
    lines = []
    lines.append("// AUTO-GENERATED by tools/gen-fields.py — DO NOT EDIT")
    lines.append("// Source: rust/core/fields.yaml")
    lines.append("")
    lines.append("use crate::field::Field;")
    lines.append("use crate::gen;")
    lines.append("")

    # REGISTRY
    lines.append("pub static REGISTRY: &[Field] = &[")
    current_group = None
    for entry in fields:
        if entry["group"] != current_group:
            current_group = entry["group"]
            lines.append(f"    // {current_group}")
        fid = entry["id"]
        name = entry["name"]
        group = entry["group"]
        desc = entry.get("description", "")
        gen_module = entry["gen"]
        lines.append(
            f'    Field::new("{fid}", "{name}", "{group}", "{desc}", gen::{gen_module}::gen),'
        )
    lines.append("];")
    lines.append("")

    # GROUPS
    lines.append("pub const GROUPS: &[&str] = &[")
    for g in groups:
        lines.append(f'    "{g}",')
    lines.append("];")
    lines.append("")

    # field_modifiers
    lines.append("pub fn field_modifiers(id: &str) -> &'static str {")
    lines.append("    match id {")
    for fid, mods in modifiers.items():
        lines.append(f'        "{fid}" => "{mods}",')
    lines.append('        _ => "",')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # field_capabilities
    lines.append("pub fn field_capabilities(id: &str) -> &'static str {")
    lines.append("    match id {")
    for fid, caps in capabilities.items():
        lines.append(f'        "{fid}" => "{caps}",')
    lines.append('        _ => "",')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    content = "\n".join(lines)
    OUT_PATH.write_text(content)

    print(
        f"Generated {OUT_PATH.name}: {len(fields)} fields, {len(groups)} groups, {len(modifiers)} modifier entries"
    )
    print(f"Next available ID: f{next_id:05d}")


if __name__ == "__main__":
    main()
