#!/usr/bin/env python3
"""Generate Python type stub (.pyi) from fields.yaml.

Output: build/types/pip/__init__.pyi
Source: rust/core/fields.yaml (single source of truth)

Every field gets a @overload on field() with its valid keyword arguments.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import field_meta

OUT = field_meta.BUILD_TYPES / "pip" / "__init__.pyi"

COMMON_KWARGS = [
    ("upper", "bool"),
    ("lower", "bool"),
    ("capitalize", "bool"),
    ("omit", "int"),
]


def generate(fields):
    lines = [
        "# AUTO-GENERATED by tools/gen-py-types.py from rust/core/fields.yaml — DO NOT EDIT",
        "",
        "from typing import Literal, overload",
        "",
        "",
        "def _build_spec(name: str, kwargs: dict) -> str: ...",
        "",
        "",
        "class SeedFaker:",
        "    def __init__(",
        "        self,",
        "        seed: str | None = ...,",
        "        locale: str | None = ...,",
        "        tz: str | None = ...,",
        "        since: int | None = ...,",
        "        until: int | None = ...,",
        "    ) -> None: ...",
        "",
    ]

    for f in fields:
        name = f["name"]
        mods = f.get("modifiers", [])
        has_range = f.get("range", False)
        has_ordering = f.get("ordering", False)
        has_length = f.get("length", False)

        params = []
        for m in mods:
            py_name = m.replace("-", "_")
            if py_name[0].isdigit():
                py_name = "r" + py_name
            params.append((py_name, "bool"))
        if has_range:
            params.append(("range", "tuple[int, int]"))
        if has_ordering:
            params.append(("asc", "bool"))
            params.append(("desc", "bool"))
        if has_length:
            params.append(("length", "int"))

        all_params = params + COMMON_KWARGS

        lines.append("    @overload")
        lines.append(f'    def field(self, name: Literal["{name}"], *,')
        for pname, ptype in all_params:
            lines.append(f"        {pname}: {ptype} = ...,")
        lines.append("    ) -> str: ...")
        lines.append("")

    # Catch-all
    lines.append("    def field(self, name: str, **kwargs: object) -> str: ...")
    lines.append("")

    # record
    lines.append("    def record(")
    lines.append("        self,")
    lines.append("        fields: list[str],")
    lines.append("        *,")
    lines.append("        ctx: str | None = ...,")
    lines.append("        corrupt: str | None = ...,")
    lines.append("    ) -> dict[str, str]: ...")
    lines.append("")

    # records
    lines.append("    def records(")
    lines.append("        self,")
    lines.append("        fields: list[str],")
    lines.append("        *,")
    lines.append("        n: int = ...,")
    lines.append("        ctx: str | None = ...,")
    lines.append("        corrupt: str | None = ...,")
    lines.append("    ) -> list[dict[str, str]]: ...")
    lines.append("")

    # validate
    lines.append("    @staticmethod")
    lines.append("    def validate(")
    lines.append("        fields: list[str],")
    lines.append("        *,")
    lines.append("        ctx: str | None = ...,")
    lines.append("        corrupt: str | None = ...,")
    lines.append("    ) -> None: ...")
    lines.append("")

    lines.append("    @staticmethod")
    lines.append("    def fields() -> list[str]: ...")
    lines.append("")
    lines.append("    @staticmethod")
    lines.append("    def fingerprint() -> str: ...")
    lines.append("")

    return "\n".join(lines)


def main():
    fields = field_meta.load()
    content = generate(fields)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(
        f"  {OUT.relative_to(field_meta.ROOT)} ({len(fields)} fields, {len(content.splitlines())} lines)"
    )


if __name__ == "__main__":
    main()
