#!/usr/bin/env python3
"""Generate Go Opts struct and buildSpec from fields.yaml.

Output: build/types/go/opts_gen.go
Source: rust/core/fields.yaml (single source of truth)

The generated file contains the Opts struct with all modifier booleans
and the buildSpec function. This guarantees that adding a modifier to
fields.yaml automatically surfaces it in the Go API.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import field_meta

OUT = field_meta.BUILD_TYPES / "go" / "opts_gen.go"


def to_go_field(mod_name: str) -> str:
    """e164 -> E164, alpha3 -> Alpha3, 1x1 -> Ratio1x1"""
    s = mod_name.replace("-", "_")
    if s[0].isdigit():
        return "Ratio" + s.title().replace("_", "")
    parts = s.split("_")
    return "".join(p.capitalize() if not p.isupper() else p.upper() for p in parts)


def generate(fields):
    # Collect all unique modifier names across all fields
    all_mods = []
    seen = set()
    for f in fields:
        for m in f.get("modifiers", []):
            if m not in seen:
                all_mods.append(m)
                seen.add(m)

    lines = [
        "// AUTO-GENERATED by tools/gen-go-types.py — DO NOT EDIT",
        "// Source: rust/core/fields.yaml",
        "",
        "package seedfaker",
        "",
        "import (",
        '\t"strconv"',
        '\t"strings"',
        ")",
        "",
        "// Opts — field-level options. Zero values = not set.",
        "type Opts struct {",
        "\tN      int    // Number of values (0 or 1 = single value)",
        "\tOmit   int    // Omit percentage (0 = no omit)",
        "\tRange  [2]int // [from, to]; both 0 = no range",
        "\tLength int    // For length-capable fields (digits, hex, etc.)",
        "\tUpper  bool",
        "\tLower  bool",
        "\tAsc    bool",
        "\tDesc   bool",
        "\tXuniq  bool",
    ]

    # Add all modifier booleans
    for m in all_mods:
        go_name = to_go_field(m)
        # Skip if already defined above (upper, lower, asc, desc, xuniq)
        if go_name.lower() in ("upper", "lower", "asc", "desc", "xuniq"):
            continue
        lines.append(f"\t{go_name} bool")

    lines.append("}")
    lines.append("")

    # buildSpec function
    lines.append("func buildSpec(name string, opts Opts) string {")
    lines.append("\tparts := []string{name}")
    lines.append("")

    # Boolean modifier flags
    lines.append("\t// Field-specific modifiers (generated from fields.yaml)")
    lines.append("\tfor _, pair := range []struct {")
    lines.append("\t\tflag bool")
    lines.append("\t\tkey  string")
    lines.append("\t}{")

    for m in all_mods:
        go_name = to_go_field(m)
        if go_name.lower() in ("upper", "lower", "asc", "desc", "xuniq"):
            continue
        lines.append(f'\t\t{{opts.{go_name}, "{m}"}},')

    # Universal transforms and ordering
    lines.append('\t\t{opts.Upper, "upper"},')
    lines.append('\t\t{opts.Lower, "lower"},')
    lines.append('\t\t{opts.Xuniq, "xuniq"},')
    lines.append('\t\t{opts.Asc, "asc"},')
    lines.append('\t\t{opts.Desc, "desc"},')
    lines.append("\t} {")
    lines.append("\t\tif pair.flag {")
    lines.append("\t\t\tparts = append(parts, pair.key)")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("")
    lines.append("\tif opts.Length > 0 {")
    lines.append("\t\tparts = append(parts, strconv.Itoa(opts.Length))")
    lines.append("\t}")
    lines.append("\tif opts.Omit > 0 {")
    lines.append('\t\tparts = append(parts, "omit="+strconv.Itoa(opts.Omit))')
    lines.append("\t}")
    lines.append("\tif opts.Range[0] != 0 || opts.Range[1] != 0 {")
    lines.append(
        '\t\tparts = append(parts, strconv.Itoa(opts.Range[0])+".."+strconv.Itoa(opts.Range[1]))'
    )
    lines.append("\t}")
    lines.append("")
    lines.append('\treturn strings.Join(parts, ":")')
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    fields = field_meta.load()
    content = generate(fields)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    mods = field_meta.all_modifiers(fields)
    print(f"  {OUT.relative_to(field_meta.ROOT)} ({len(mods)} modifiers)")


if __name__ == "__main__":
    main()
