#!/usr/bin/env python3
"""Generate TypeScript type definitions from fields.yaml.

Output: build/types/npm/index.d.ts
Source: rust/core/fields.yaml (single source of truth)

Every field gets a typed overload on field(). Fields with modifiers, range,
ordering, or length get a custom opts interface; others use BaseOpts.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import field_meta

OUT = field_meta.BUILD_TYPES / "npm" / "index.d.ts"


def generate(fields):
    lines = [
        "// AUTO-GENERATED by tools/gen-ts-types.py — DO NOT EDIT",
        "// Source: rust/core/fields.yaml",
        "",
        "export interface FakerOptions {",
        "  seed?: string;",
        "  locale?: string;",
        "  tz?: string;",
        "  since?: number;",
        "  until?: number;",
        "}",
        "",
        "interface BaseOpts {",
        "  upper?: true;",
        "  lower?: true;",
        "  capitalize?: true;",
        "  omit?: number;",
        "}",
        "",
    ]

    # Per-field interfaces
    custom_ifaces = {}
    for f in fields:
        name = f["name"]
        mods = f.get("modifiers", [])
        has_range = f.get("range", False)
        has_ordering = f.get("ordering", False)
        has_length = f.get("length", False)

        if not mods and not has_range and not has_ordering and not has_length:
            continue

        iface = field_meta.to_pascal(name) + "Opts"
        custom_ifaces[name] = iface
        members = []

        for m in mods:
            key = m.replace("-", "_")
            if key[0].isdigit():
                members.append(f'  "{key}"?: true;')
            else:
                members.append(f"  {key}?: true;")

        if has_range:
            members.append("  range?: [number, number];")
        if has_ordering:
            members.append("  asc?: true;")
            members.append("  desc?: true;")
        if has_length:
            members.append("  length?: number;")

        lines.append(f"interface {iface} extends BaseOpts {{")
        lines.extend(members)
        lines.append("}")
        lines.append("")

    # FieldName union
    names = field_meta.field_names(fields)
    lines.append("export type FieldName =")
    for i, n in enumerate(names):
        sep = ";" if i == len(names) - 1 else ""
        lines.append(f'  | "{n}"{sep}')
    lines.append("")

    # RecordOpts + ValidateOpts
    lines.append("export interface RecordOpts {")
    lines.append("  n?: number;")
    lines.append('  ctx?: "strict" | "loose";')
    lines.append('  corrupt?: "low" | "mid" | "high" | "extreme";')
    lines.append("}")
    lines.append("")
    lines.append("export interface ValidateOpts {")
    lines.append('  ctx?: "strict" | "loose";')
    lines.append('  corrupt?: "low" | "mid" | "high" | "extreme";')
    lines.append("}")
    lines.append("")

    # SeedFaker class
    lines.append("export class SeedFaker {")
    lines.append("  constructor(opts?: FakerOptions);")
    lines.append("")

    for name in names:
        opts_type = custom_ifaces.get(name, "BaseOpts")
        lines.append(f'  field(name: "{name}", opts?: {opts_type}): string;')

    lines.append("  field(name: string, opts?: BaseOpts): string;")
    lines.append("")
    lines.append(
        "  record("
        "fields: (FieldName | string)[], "
        "opts?: ValidateOpts"
        "): Record<string, string>;"
    )
    lines.append("")
    lines.append(
        "  records("
        "fields: (FieldName | string)[], "
        "opts?: RecordOpts"
        "): Record<string, string>[];"
    )
    lines.append("")
    lines.append(
        "  validate(fields: (FieldName | string)[], opts?: ValidateOpts): void;"
    )
    lines.append("")
    lines.append("  static fields(): FieldName[];")
    lines.append("  static fingerprint(): string;")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


def main():
    fields = field_meta.load()
    content = generate(fields)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content)
    print(
        f"  {OUT.relative_to(field_meta.ROOT)} ({len(fields)} fields, {len(content.splitlines())} lines)"
    )


if __name__ == "__main__":
    main()
